{% set version = "10.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-msigdbr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/msigdbr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/msigdbr/msigdbr_{{ version }}.tar.gz
  sha256: ce4f74195ad2bf6a8be6fb1f9137887b9b11667a45dc8f1300028f19afb0214a

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-babelgene
    - r-dplyr >=0.7.0
    - r-magrittr
    - r-rlang
    - r-tibble
    - r-tidyselect
  run:
    - r-base
    - r-babelgene
    - r-dplyr >=0.7.0
    - r-magrittr
    - r-rlang
    - r-tibble
    - r-tidyselect

test:
  commands:
    - $R -e "library('msigdbr')"           # [not win]
    - "\"%R%\" -e \"library('msigdbr')\""  # [win]

about:
  home: https://github.com/igordot/msigdbr
  license: MIT
  summary: Provides the 'Molecular Signatures Database' (MSigDB) gene sets typically used with the 'Gene Set Enrichment Analysis' (GSEA) software (Subramanian et al. 2005 <doi:10.1073/pnas.0506580102>, Liberzon et al. 2015 <doi:10.1016/j.cels.2015.12.004>) in a standard R data frame with key-value pairs. Included are the
    original human gene symbols and Entrez IDs as well as the equivalents for various frequently studied model organisms such as mouse, rat, pig, fly, and yeast.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: msigdbr
# Type: Package
# Title: MSigDB Gene Sets for Multiple Organisms in a Tidy Data Format
# Version: 6.2.1
# Authors@R: person("Igor", "Dolgalev", email = "igor.dolgalev@nyumc.org", role = c("aut", "cre"))
# Description: Provides the 'Molecular Signatures Database' (MSigDB) gene sets typically used with the 'Gene Set Enrichment Analysis' (GSEA) software (Subramanian et al. 2005 <doi:10.1073/pnas.0506580102>, Liberzon et al. 2015 <doi:10.1016/j.cels.2015.12.004>) in a standard R data frame with key-value pairs. Included are the original human gene symbols and Entrez IDs as well as the equivalents for various frequently studied model organisms such as mouse, rat, pig, fly, and yeast.
# License: MIT + file LICENSE
# Encoding: UTF-8
# URL: https://github.com/igordot/msigdbr
# BugReports: https://github.com/igordot/msigdbr/issues
# LazyData: true
# Depends: R (>= 3.2.0), dplyr (>= 0.7.0), tibble
# Imports: magrittr, rlang
# Suggests: testthat, knitr, rmarkdown
# RoxygenNote: 6.1.0
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-10-09 16:14:28 UTC; id460
# Author: Igor Dolgalev [aut, cre]
# Maintainer: Igor Dolgalev <igor.dolgalev@nyumc.org>
# Repository: CRAN
# Date/Publication: 2018-10-09 21:50:02 UTC
