appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: NlLCtge0lHlyy4DatW4vdZniHZkNJa8Qb6zliADq10LNEn1VMFOI4CGPyJNVaGmM/g5JKSwhcu2Pd83/yundmc136oYu0mgEwoZBC26NQVfTssLbezVckpbtDb1SMz/p/d+/sOUjB/lXhHw4BVcd8ZNUe8ugiH0XD5ReJ3o+MzfDzqQ0G3mbbph1PxcFRs/sFJWhimKjIryKd+OlHXypRUgnNl8YqxvLlezJufp8IAeGsde9s61WXdDA2XkiPHU6EuBmQaywJp0E3oCuQDhG2HIB+rllFcpLFpvYLcxCHkKYciLxsL0TdfdXKY8OZ6hbqM9UfCJxkKxBbxUhE32izC+U2Qu2G/5Jm0C/90+lF/E9qPnJLd+fJYXdEmWudhrLAm1YHu75fIjxHwzivYx6LwEDmt1Ye5QRMUVYHPE3wHlyTXvzkzq94FKmzn30uXzIKS7/FKc5Wgj1/SWPEeRIDWtbBhJ0lsLUWt9lP/098cli43Wt2MANoMPqL3J0DLkd9DMgBNFx3pFmscNIlOp6UE4jV0mBnKoVoihc2jrowconr2SOGooVHpQy88nS4DJfkowTQaA7OiuyyFwVwFqJuJwrf5aMjZVhprahduYTgGQun9ZSzTbKNtLt6GMJSrYlqu9oXaQgQk/ZzSrIm9q8pDGzSvS9YNik41LCjNcKBQA=
